version: '3.2'

services:
  nexus:
      image: sonatype/nexus3:3.12.1
      volumes:
      - nexus_data:/nexus-data
      ports:
      - 8091:8081
      networks:
      - backend
  
networks:
  backend:
    driver: bridge

volumes: 
  jenkins_data:
  nexus_data:
